DB password: SdhsTemp123A-


spring.datasource.url=jdbc:postgresql://localhost:5432/sdhs_db
spring.datasource.username=madhan
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect